server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # \u6CE8\u518C\u81EA\u5DF1\u5230 eureka
    fetch-registry: false # \u4ECE\u6CE8\u518C\u4E2D\u5FC3\u6293\u53D6\u670D\u52A1\u5217\u8868\u6E05\u5355
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # \u6CE8\u518C\u4E2D\u5FC3\u5730\u5740